public enum Shape {

    SINGLE_CELL,
    TWO_CELL,
    THREE_CELL_STRAIGHT,
    THREE_CELL_CURVED,
    FOUR_CELL_STRAIGHT,
    SQUARE,
    FOUR_CELL_ZIG,
    FOUR_CELL_MIRROR_L,
    PYRAMID,
    FOUR_CELL_L;
}
